export { default as Logo } from './Logo.vue'
export { default as ModelPicture } from './ModelPicture.vue'
export { default as HeroTitle } from './HeroTitle.vue'
export { default as HeroParagraph } from './HeroParagraph.vue'
export { default as NewsForm } from './NewsForm.vue'
export { default as ModelPictureMobile } from './ModelPictureMobile.vue'
